### PR TITLE
Add support for outcodes lookup

### PR DESCRIPTION
**Pull request by neilbmclaughlin**

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
I did consider adding logic to the `lookup` method which allows either a postcode or an outcode to be passed to it. This has a certain elegance but the difference in postcode and outcode response objects meant that I discounted it as it seems like it could be a breaking change. Happy to reconsider this decision however.

**Comment by neilbmclaughlin** [comment]
@billinghamj - do you think you will accept this PR?

**Comment by billinghamj** [comment]
Sorry I somehow missed this. Just reviewing now

**Comment by billinghamj** [comment]
Although it's no longer a style I would really condone, in the spirit of following the existing explicit/implicit thing going on with `near`, I'd suggest changing the API a bit.

Really this function is for looking up an outcode, so I feel just `.outcode` is not quite right. But there is already a `lookup` function.

Thus, I'd suggest the following:

```js
postcodes.lookup('EC2A 4DP');
postcodes.lookup('EC2A');
postcodes.lookupPostcode('EC2A 4DP');
postcodes.lookupOutcode('EC2A');
```

So the standard `lookup` function uses the [postcode](https://www.npmjs.com/package/postcode) npm package to determine whether it is an outcode or postcode, then uses the relevant explicit function.

**Comment by neilbmclaughlin** [comment]
I've not added tests for the logic which sits inside of `postcodes.lookup` since `postcode.near` doesn't have tests. Would be happy to add tests (using `rewire` + `sinon` or integration tests) to achieve this for both if you think there is value in it.

I'd prefer to do this as a separate PR.

**Comment by billinghamj** [comment]
Please remove the package.lock, revert the whitespace changes to package.json and update the README with the new changes, then it's good to go. Thanks :)

**Comment by billinghamj** [comment]
Agree tests on .lookup can wait

**Comment by neilbmclaughlin** [comment]
Just spotted a tabs vs space issue which I'll fix ASAP.

**Comment by neilbmclaughlin** [comment]
Tabs vs space issue fixed.

**Comment by billinghamj** [comment]
Sorry just one final issue to fix which seems to have come about somehow. `postcodes` has been renamed to `data` for all the other methods in the README - https://github.com/billinghamj/postcodesio-client-node/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8L163

**Comment by billinghamj** [comment]
Don't worry about force-pushing, as I will squash merge

**Comment by billinghamj** [comment]
Ah also, in the README, the example result for the outcode type isn't correct. Only the `result` object is returned - not the outer object including status etc

**Comment by neilbmclaughlin** [comment]
Changes made. Good spot with the example error. Had changed return values to `data` since the type(s) were specified in the description but changed this back now.

**Comment by billinghamj** [comment]
Thanks 👍🏼 Will sort out a new version tomorrow

**Comment by billinghamj** [comment]
That's released now as v0.2.0

**Pull request merged**
